; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	madhephaestus/ESP32Encoder@^0.12.0
	adafruit/Adafruit ADS1X15@^2.6.2
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	mikalhart/TinyGPSPlus@^1.1.0
	vshymanskyy/TinyGSM@^0.12.0
	arduino-libraries/ArduinoHttpClient@^0.6.1
	bblanchon/ArduinoJson@^7.2.2
board_build.flash_mode = dio
monitor_speed = 115200

; ปกติให้คอมไพล์ทุกอย่างใน src (ไม่ต้องสั่งลบ test-module แล้วเพราะมันอยู่ข้างนอก)
build_src_filter = +<*> -<.git/> -<.svn/> -<tests/>

[env:Sensor_1]
build_flags = 
	-D SENSOR_COUNT=1

[env:Sensor_3]
build_flags = 
	-D SENSOR_COUNT=3

